#!/usr/bin/env python3
# Copyright (c) 2026 Unfolded Circle ApS and/or its affiliates. <hello@unfoldedcircle.com>
# SPDX-License-Identifier: GPL-3.0-or-later
"""Builds and verifies the embedded icon font. See docs/icon-font.md.

The app embeds exactly one icon font, `resources/icons/icon-font.ttf`, built from a Font
Awesome webfont:

  build   patch a source webfont and write it with its provenance file
  check   verify the tracked font against its provenance (used by CI and by the build)
  info    print what a font file contains

Patching does two things:

1. Emoji code points are unmapped. Font Awesome maps a few hundred emoji code points to
   icon glyphs, so any text containing an emoji would render as icons.
2. The font is renamed. Font Awesome Free is SIL OFL 1.1 with the Reserved Font Name
   "Font Awesome", so a modified version must not carry that name. Both editions are
   renamed to the same family, which keeps the QML independent of the edition.

Requires fontTools (`pip install fonttools`). Only needed to rebuild the font, not to
build the app.
"""

import argparse
import datetime
import hashlib
import json
import os
import re
import sys
import urllib.request

FAMILY = "UC Icons"
PS_NAME = "UCIcons"
EMOJI_BASE = "https://unicode.org/Public/emoji/15.1/"
EMOJI_FILES = ["emoji-sequences.txt", "emoji-zwj-sequences.txt"]
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = os.path.join(ROOT, "resources", "icons", "icon-font.ttf")
PROVENANCE = os.path.join(ROOT, "resources", "icons", "icon-font.json")


def sha256(path):
    with open(path, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest()


def emoji_codepoints(cache_dir=None):
    """Code points of every emoji sequence, from the Unicode data files."""
    points = set()
    for name in EMOJI_FILES:
        cached = os.path.join(cache_dir, name) if cache_dir else None
        if cached and os.path.exists(cached):
            with open(cached, encoding="utf-8") as handle:
                text = handle.read()
        else:
            with urllib.request.urlopen(EMOJI_BASE + name) as response:
                text = response.read().decode("utf-8")
            if cached:
                with open(cached, "w", encoding="utf-8") as handle:
                    handle.write(text)
        for line in text.splitlines():
            line = line.split("#")[0].strip()
            if not line:
                continue
            field = line.split(";")[0].strip()
            if ".." in field:
                start, end = field.split("..")
                points.update(range(int(start, 16), int(end, 16) + 1))
            else:
                points.update(int(part, 16) for part in field.split())
    return points


def font_names(font):
    """The name table entries of interest, as {nameID: text}."""
    out = {}
    for record in font["name"].names:
        if record.nameID in (1, 2, 4, 5, 6, 16, 17) and record.nameID not in out:
            out[record.nameID] = record.toUnicode()
    return out


def cmd_info(args):
    from fontTools.ttLib import TTFont

    font = TTFont(args.font, lazy=True)
    names = font_names(font)
    print(f"file:        {args.font}")
    print(f"sha256:      {sha256(args.font)}")
    print(f"format:      {'OpenType/CFF' if font.sfntVersion == 'OTTO' else 'TrueType'}")
    print(f"family:      {names.get(1)} ({names.get(2)})")
    print(f"version:     {names.get(5)}")
    print(f"glyphs:      {font['maxp'].numGlyphs}")
    print(f"code points: {len(font.getBestCmap())}")
    return 0


def cmd_build(args):
    from fontTools.ttLib import TTFont

    source = args.source
    font = TTFont(source)
    original = font_names(font)

    match = re.search(r"Font Awesome version:\s*([0-9.]+)", original.get(5, ""))
    fa_version = match.group(1) if match else "unknown"
    edition = args.edition
    if edition is None:
        edition = "pro" if "Pro" in original.get(1, "") else "free"

    emoji = emoji_codepoints(args.emoji_cache)
    removed = set()
    for table in font["cmap"].tables:
        for codepoint in [cp for cp in table.cmap if cp in emoji]:
            removed.add(codepoint)
            del table.cmap[codepoint]

    subfamily = "Regular"
    unique = f"{FAMILY}; {fa_version} {original.get(2, '')}".strip()
    for name_id, value in ((1, FAMILY), (2, subfamily), (3, unique), (4, FAMILY),
                           (6, PS_NAME), (16, FAMILY), (17, subfamily)):
        font["name"].setName(value, name_id, 3, 1, 0x409)
        font["name"].setName(value, name_id, 1, 0, 0)
    if "CFF " in font:
        font["CFF "].cff.fontNames = [PS_NAME]

    font.save(args.output)

    provenance = {
        "comment": "Generated by tools/icon-font.py. See docs/icon-font.md.",
        "edition": edition,
        "fontAwesomeVersion": fa_version,
        "sourceFamily": original.get(1),
        "sourceStyle": original.get(2),
        "sourceVersion": original.get(5),
        "sourceFile": os.path.basename(source),
        "sourceSha256": sha256(source),
        "family": FAMILY,
        "emojiCodePointsRemoved": len(removed),
        "codePoints": len(TTFont(args.output, lazy=True).getBestCmap()),
        "sha256": sha256(args.output),
        "builtOn": datetime.date.today().isoformat(),
    }
    with open(args.provenance, "w", encoding="utf-8") as handle:
        json.dump(provenance, handle, indent=2, sort_keys=True)
        handle.write("\n")

    print(f"[+] {args.output}: {edition} edition, Font Awesome {fa_version}, "
          f"{provenance['codePoints']} code points, {len(removed)} emoji code points unmapped")
    print(f"[+] {args.provenance}")
    if edition == "pro":
        print("[!] Commercially licensed font: never commit this file or its provenance.")
    return 0


def cmd_check(args):
    """Verifies the font against its provenance. Returns non-zero on a mismatch."""
    from fontTools.ttLib import TTFont

    with open(args.provenance, encoding="utf-8") as handle:
        provenance = json.load(handle)
    problems = []

    actual = sha256(args.font)
    if actual != provenance["sha256"]:
        problems.append(f"{args.font} does not match its provenance file "
                        f"(sha256 {actual}, expected {provenance['sha256']})")

    font = TTFont(args.font, lazy=True)
    names = font_names(font)
    if names.get(1) != provenance["family"]:
        problems.append(f"family is '{names.get(1)}', expected '{provenance['family']}'")
    # OFL 1.1 forbids the Reserved Font Name in the *names* of a modified version. The
    # copyright (0), version (5) and license (13, 14) entries keep it and must stay intact.
    for name_id in (1, 2, 4, 6, 16, 17):
        if "Font Awesome" in (names.get(name_id) or ""):
            problems.append(f"the Reserved Font Name 'Font Awesome' is still in name ID {name_id}")

    if args.require_free:
        if provenance["edition"] != "free":
            problems.append(f"edition is '{provenance['edition']}', expected 'free'")
        if "Pro" in (provenance.get("sourceFamily") or ""):
            problems.append(f"built from a Pro font: {provenance.get('sourceFamily')}")

    for problem in problems:
        print(f"error: {problem}", file=sys.stderr)
    if problems:
        return 1
    print(f"[+] {os.path.basename(args.font)}: {provenance['edition']} edition, "
          f"Font Awesome {provenance['fontAwesomeVersion']}, family '{provenance['family']}'")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)

    build = sub.add_parser("build", help="patch a source webfont into the embedded icon font")
    build.add_argument("source", help="Font Awesome webfont, e.g. webfonts/fa-solid-900.ttf")
    build.add_argument("-o", "--output", default=FONT)
    build.add_argument("-p", "--provenance", default=PROVENANCE)
    build.add_argument("--edition", choices=["free", "pro"], default=None)
    build.add_argument("--emoji-cache", default=None, help="directory for the Unicode emoji data files")
    build.set_defaults(func=cmd_build)

    check = sub.add_parser("check", help="verify the font against its provenance file")
    check.add_argument("-f", "--font", default=FONT)
    check.add_argument("-p", "--provenance", default=PROVENANCE)
    check.add_argument("--require-free", action="store_true", help="also fail if the font is not the Free edition")
    check.set_defaults(func=cmd_check)

    info = sub.add_parser("info", help="print what a font file contains")
    info.add_argument("font")
    info.set_defaults(func=cmd_info)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
