// Copyright (c) 2022-2023 Unfolded Circle ApS and/or its affiliates. <hello@unfoldedcircle.com>
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(lcApp);
Q_DECLARE_LOGGING_CATEGORY(lcI18n);
Q_DECLARE_LOGGING_CATEGORY(lcCore);
Q_DECLARE_LOGGING_CATEGORY(lcConfig);
Q_DECLARE_LOGGING_CATEGORY(lcVoice);
Q_DECLARE_LOGGING_CATEGORY(lcSoftwareUpdate);

Q_DECLARE_LOGGING_CATEGORY(lcUi);
Q_DECLARE_LOGGING_CATEGORY(lcResources);
Q_DECLARE_LOGGING_CATEGORY(lcPage);
Q_DECLARE_LOGGING_CATEGORY(lcGroup);
Q_DECLARE_LOGGING_CATEGORY(lcInput);
Q_DECLARE_LOGGING_CATEGORY(lcNotification);
Q_DECLARE_LOGGING_CATEGORY(lcOnboarding);

Q_DECLARE_LOGGING_CATEGORY(lcEntityController);
Q_DECLARE_LOGGING_CATEGORY(lcEntities);
Q_DECLARE_LOGGING_CATEGORY(lcGroupController);
Q_DECLARE_LOGGING_CATEGORY(lcIntegrationController);
Q_DECLARE_LOGGING_CATEGORY(lcIntegrationDriver);

Q_DECLARE_LOGGING_CATEGORY(lcDockController);

Q_DECLARE_LOGGING_CATEGORY(lcHw);
Q_DECLARE_LOGGING_CATEGORY(lcHwHaptic);
Q_DECLARE_LOGGING_CATEGORY(lcHwBattery);
Q_DECLARE_LOGGING_CATEGORY(lcHwMic);
Q_DECLARE_LOGGING_CATEGORY(lcHwWifi);
Q_DECLARE_LOGGING_CATEGORY(lcHwTouchSlider);

Q_DECLARE_LOGGING_CATEGORY(lcEntity);
Q_DECLARE_LOGGING_CATEGORY(lcLight);
Q_DECLARE_LOGGING_CATEGORY(lcButton);
Q_DECLARE_LOGGING_CATEGORY(lcSwitch);
Q_DECLARE_LOGGING_CATEGORY(lcClimate);
Q_DECLARE_LOGGING_CATEGORY(lcCover);
Q_DECLARE_LOGGING_CATEGORY(lcSensor);
Q_DECLARE_LOGGING_CATEGORY(lcMediaPlayer);
Q_DECLARE_LOGGING_CATEGORY(lcActivity);
Q_DECLARE_LOGGING_CATEGORY(lcMacro);
Q_DECLARE_LOGGING_CATEGORY(lcRemote);
Q_DECLARE_LOGGING_CATEGORY(lcVoiceAssistant);
